### ISSUE TITLE
Error: too many values to unpack in down.py

### ISSUE THREAD

**Issue by zajax** [appnexus/schema-tool#69]
$ schema rebuild -f
Bringing all the way down
An exception has occurred... Sorry. You should file a ticket in
our issue tracker: http://github.com/appnexus/schema-tool/issues

Error: too many values to unpack

Traceback (most recent call last):
  File "/Users/bzajac/bin/schema", line 95, in main
    globals()[handler](context).run()
  File "/Volumes/Code/schema-tool/schematool/command/rebuild.py", line 32, in run
    DownCommand(self.context).run()
  File "/Volumes/Code/schema-tool/schematool/command/down.py", line 64, in run
    for (_, alter_id, _) in history:
ValueError: too many values to unpack

**Comment by zajax** [comment]
A dump of the history object in down.py shows that the tuples are 4 values:

 (12, u'137995138890', None, datetime.datetime(2016, 1, 24, 14, 7, 2)),
 (11, u'137963939290', None, datetime.datetime(2016, 1, 24, 14, 7, 1)),
 (10, u'137962014040', None, datetime.datetime(2016, 1, 24, 14, 7, 1)),
 (9, u'137960428730', None, datetime.datetime(2016, 1, 24, 14, 7, 1)),
 (8, u'137951455650', None, datetime.datetime(2016, 1, 24, 14, 7, 1)),
 (7, u'137894835110', None, datetime.datetime(2016, 1, 24, 14, 7, 1)),
 (6, u'137893701110', None, datetime.datetime(2016, 1, 24, 14, 7, 1)),
 (5, u'137899468930', None, datetime.datetime(2016, 1, 24, 14, 7, 1)),
 (4, u'137892415610', None, datetime.datetime(2016, 1, 24, 14, 7)),
 (3, u'137882703950', None, datetime.datetime(2016, 1, 24, 14, 7)),
 (2, u'137873917970', None, datetime.datetime(2016, 1, 24, 14, 7)),
 (1, u'137823105930', None, datetime.datetime(2016, 1, 24, 14, 7))]

In down.py, it only looks for 3 in unpacking: for (_, alter_id, _) in history:
